export function createEmployeeData() {
    return {
        personalData: {
            firstName: "John",
            lastName: "Doe",
            email: "john.doe@email.com",
            phone: "123456789",
            pesel: "123456789",
            clothSize: "M",
            nip: 123456789,
            personalDataHistory: [
                {
                    firstNameBefore: "John",
                    firstNameAfter: "John",
                    lastNameBefore: "Doe",
                    lastNameAfter: "Doe",
                    emailBefore: "john.doe@email.com",
                    emailAfter: "john.doe@email.com",
                    phoneBefore: 123456789,
                    phoneAfter: 123456789,
                    peselBefore: "123456789",
                    peselAfter: "123456789",
                    clothSizeBefore: "M",
                    clothSizeAfter: "M",
                    nipBefore: "123456789",
                    nipAfter: "123456789",
                    changeDate: new Date().toLocaleDateString(),
                },
            ],
            address1: {
                street1: "street",
                house1: "house",
                city1: "city",
                state1: "state",
                zip1: "zip",
                voivodeship1: "voivodeship",
                address1History: [
                    {
                        street1Before: "street",
                        street1After: "street",
                        house1Before: "house",
                        house1After: "house",
                        city1Before: "city",
                        city1After: "city",
                        state1Before: "state",
                        state1After: "state",
                        zip1Before: "zip",
                        zip1After: "zip",
                        voivodeship1Before: "voivodeship",
                        voivodeship1After: "voivodeship",
                        changeDate: new Date().toLocaleDateString(),
                    },
                ],
            },
            address2: {
                street2: "street",
                house2: "house",
                city2: "city",
                state2: "state",
                zip2: "zip",
                voivodeship2: "voivodeship",
                address2History: [
                    {
                        street2Before: "street",
                        street2After: "street",
                        house2Before: "house",
                        house2After: "house",
                        city2Before: "city",
                        city2After: "city",
                        state2Before: "state",
                        state2After: "state",
                        zip2Before: "zip",
                        zip2After: "zip",
                        voivodeship2Before: "voivodeship",
                        voivodeship2After: "voivodeship",
                        changeDate: new Date().toLocaleDateString(),
                    },
                ],
            },
        },
        jobDetails: {
            status: "active",
            jobTitle: "developer",
            department: "IT",
            startDate: new Date().toLocaleDateString(),
            endDate: null,
            contractType: "full-time",
            workSchedule: "daily",
            insuranceType: "commercial",
            annualLeaveDays: 26,
            jobDetailsHistory: [
                {
                    statusBefore: "active",
                    statusAfter: "active",
                    jobTitleBefore: "developer",
                    jobTitleAfter: "developer",
                    departmentBefore: "IT",
                    departmentAfter: "IT",
                    startDateBefore: new Date().toLocaleDateString(),
                    startDateAfter: new Date().toLocaleDateString(),
                    endDateBefore: null,
                    endDateAfter: null,
                    contractTypeBefore: "full-time",
                    contractTypeAfter: "full-time",
                    workScheduleBefore: "daily",
                    workScheduleAfter: "daily",
                    insuranceTypeBefore: "commercial",
                    insuranceTypeAfter: "commercial",
                    annualLeaveDaysBefore: 26,
                    annualLeaveDaysAfter: 26,
                    changeDate: new Date().toLocaleDateString(),
                },
            ],
            jobStayAddress: {
                street: "street",
                house: "house",
                city: "city",
                state: "state",
                zip: "zip",
                voivodeship: "voivodeship",
                jobStayAddressHistory: [
                    {
                        streetBefore: "street",
                        streetAfter: "street",
                        houseBefore: "house",
                        houseAfter: "house",
                        cityBefore: "city",
                        cityAfter: "city",
                        stateBefore: "state",
                        stateAfter: "state",
                        zipBefore: "zip",
                        zipAfter: "zip",
                        voivodeshipBefore: "voivodeship",
                        voivodeshipAfter: "voivodeship",
                        changeDate: new Date().toLocaleDateString(),
                    },
                ],
            },
            salary: {
                baseSalary: 4000,
                currency: "EUR",
                hourlyRate: "40",
                bankAccount: "12345678901234567890123456",
                bankName: "bank",
                salaryHistory: [
                    {
                        baseSalaryBefore: 4000,
                        baseSalaryAfter: 4000,
                        currencyBefore: "EUR",
                        currencyAfter: "EUR",
                        hourlyRateBefore: 40,
                        hourlyRateAfter: 40,
                        bankAccountBefore: "12345678901234567890123456",
                        bankAccountAfter: "12345678901234567890123456",
                        bankNameBefore: "bank",
                        bankNameAfter: "bank",
                        changeDate: new Date().toLocaleDateString(),
                    },
                ],
            },
        },
    };
}