version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=test
    networks:
      - mongodb_network
    volumes:
      - mongodb_data:/data/db
    restart: always

networks:
  mongodb_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
