name: Deno

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
        - name: Clone repository
          uses: actions/checkout@v4

        - name: Install Deno
          uses: denoland/setup-deno@v2
          with:
            deno-version: v2.x

        - name: Test
          run: deno test --allow-net --allow-read --allow-env

  deploy:
    needs: [test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
        - name: Clone repository
          uses: actions/checkout@v4

        - name: Install Deno
          uses: denoland/setup-deno@v2
          with:
            deno-version: v2.x

        - name: Upload to Deno Deploy
          uses: denoland/deployctl@v1
          with:
            project: "hrithmia-api"
            entrypoint: "main.ts"
            root: "."
          env:
            DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
